"""Pin the uploaded model repo and the ONNX Runtime 1.22.0 packages into
crates/kode-local/src/pins.rs (sha256 + size of every artefact).

Usage: python scripts/local-models/gen_pins.py <hf-repo-id>
"""
import hashlib
import io
import os
import re
import sys
import tarfile
import urllib.request
import zipfile

from huggingface_hub import HfApi, hf_hub_download

REPO = sys.argv[1]
ORT = "1.22.0"
GH = "https://github.com/microsoft/onnxruntime/releases/download/v%s/" % ORT
NUGET = "https://www.nuget.org/api/v2/package/"
OUT = os.path.join("crates", "kode-local", "src", "pins.rs")


def sha(data):
    return hashlib.sha256(data).hexdigest()


def fetch(url):
    with urllib.request.urlopen(url) as r:
        return r.read()


def names(data, url):
    if url.endswith(".tgz"):
        with tarfile.open(fileobj=io.BytesIO(data)) as t:
            return set(t.getnames())
    with zipfile.ZipFile(io.BytesIO(data)) as z:
        return set(z.namelist())


api = HfApi()
revision = api.model_info(REPO).sha
files = sorted(f for f in api.list_repo_files(REPO, revision=revision)
               if f.startswith(("laya-multilingual/", "qwen3-reranker-0.6b/")))
model_pins = []
for f in files:
    p = hf_hub_download(REPO, f, revision=revision)
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    model_pins.append((f, h.hexdigest(), os.path.getsize(p)))

dml_ort = NUGET + "Microsoft.ML.OnnxRuntime.DirectML/" + ORT
dml_ort_data = fetch(dml_ort)
with zipfile.ZipFile(io.BytesIO(dml_ort_data)) as z:
    nuspec = z.read(next(n for n in z.namelist() if n.endswith(".nuspec"))).decode()
dml_version = re.search(r'id="Microsoft\.AI\.DirectML"\s+version="\[?([0-9.]+)', nuspec).group(1)
dml = NUGET + "Microsoft.AI.DirectML/" + dml_version

RUNTIMES = [
    ("linux", "x86_64", "cpu", [GH + "onnxruntime-linux-x64-%s.tgz" % ORT],
     "onnxruntime-linux-x64-%s/lib/libonnxruntime.so.%s" % (ORT, ORT), []),
    ("linux", "x86_64", "gpu", [GH + "onnxruntime-linux-x64-gpu-%s.tgz" % ORT],
     "onnxruntime-linux-x64-gpu-%s/lib/libonnxruntime.so.%s" % (ORT, ORT), []),
    ("linux", "aarch64", "cpu", [GH + "onnxruntime-linux-aarch64-%s.tgz" % ORT],
     "onnxruntime-linux-aarch64-%s/lib/libonnxruntime.so.%s" % (ORT, ORT), []),
    ("macos", "aarch64", "coreml", [GH + "onnxruntime-osx-arm64-%s.tgz" % ORT],
     "onnxruntime-osx-arm64-%s/lib/libonnxruntime.%s.dylib" % (ORT, ORT), []),
    ("windows", "x86_64", "directml", [dml_ort, dml],
     "runtimes/win-x64/native/onnxruntime.dll", ["bin/x64-win/DirectML.dll"]),
]

rt_pins = []
for os_, arch, variant, urls, dylib, colocate in RUNTIMES:
    archives, contents = [], set()
    for u in urls:
        data = dml_ort_data if u == dml_ort else fetch(u)
        archives.append((u, sha(data), len(data)))
        contents |= names(data, u)
    for needed in [dylib] + colocate:
        assert needed in contents, "%s missing from %s" % (needed, urls)
    rt_pins.append((os_, arch, variant, archives, dylib, colocate))

lines = [
    "//! @generated by scripts/local-models/gen_pins.py — do not edit by hand.",
    "",
    "use crate::models::{Archive, PinnedFile, RuntimePin};",
    "",
    'pub const MODELS_REPO: &str = "%s";' % REPO,
    'pub const MODELS_REVISION: &str = "%s";' % revision,
    'pub const ORT_VERSION: &str = "%s";' % ORT,
    "",
    "pub const MODEL_FILES: &[PinnedFile] = &[",
]
for f, h, n in model_pins:
    lines.append('    PinnedFile { path: "%s", sha256: "%s", size: %d },' % (f, h, n))
lines += ["];", "", "pub const RUNTIMES: &[RuntimePin] = &["]
for os_, arch, variant, archives, dylib, colocate in rt_pins:
    lines.append('    RuntimePin {')
    lines.append('        os: "%s", arch: "%s", variant: "%s",' % (os_, arch, variant))
    lines.append("        archives: &[")
    for u, h, n in archives:
        lines.append('            Archive { url: "%s", sha256: "%s", size: %d },' % (u, h, n))
    lines.append("        ],")
    lines.append('        dylib: "%s",' % dylib)
    lines.append("        colocate: &[%s]," % ", ".join('"%s"' % c for c in colocate))
    lines.append("    },")
lines += ["];", ""]
with open(OUT, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print("wrote", OUT, "revision", revision)
