[package]
name = "kode-local"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
kode-core = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
futures = { workspace = true }
sha2 = { workspace = true }
ort = { version = "=2.0.0-rc.10", default-features = false, features = ["load-dynamic", "directml", "cuda", "coreml"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
