//! @generated by scripts/local-models/gen_pins.py — do not edit by hand.
//! Bootstrap content: nothing pinned yet, so `kode setup` reports NotPinned.

use crate::models::{PinnedFile, RuntimePin};

pub const MODELS_REPO: &str = "";
pub const MODELS_REVISION: &str = "";
pub const ORT_VERSION: &str = "1.22.0";
pub const MODEL_FILES: &[PinnedFile] = &[];
pub const RUNTIMES: &[RuntimePin] = &[];
