//! @generated by scripts/local-models/gen_pins.py — do not edit by hand.

use crate::models::{Archive, PinnedFile, RuntimePin};

pub const MODELS_REPO: &str = "sutantodadang/kode-local-models";
pub const MODELS_REVISION: &str = "06065571de7cbd6d2ddcbb3f938e5bd5457fc4a6";
pub const ORT_VERSION: &str = "1.22.0";

pub const MODEL_FILES: &[PinnedFile] = &[
    PinnedFile {
        path: "laya-multilingual/laya.json",
        sha256: "fa9fd1afb25360c2860b60b2d10ddcb605e540652e4d6151a98e56f0c1e93248",
        size: 164,
    },
    PinnedFile {
        path: "laya-multilingual/model.onnx",
        sha256: "145726addf2365f25537df6f71cea9b4cfc4d9eb2b43870debc1411949cd3b03",
        size: 1287466242,
    },
    PinnedFile {
        path: "laya-multilingual/tokenizer.json",
        sha256: "609d8f4c067cd3950f88594c5a802616cea245823836ef5848ee4fc40aab5b6f",
        size: 34363188,
    },
    PinnedFile {
        path: "qwen3-reranker-0.6b/model.onnx",
        sha256: "a49d7607c07aa79fc55613553d29dc497438edc4543c4a787c15b1f3918098c4",
        size: 1369130,
    },
    PinnedFile {
        path: "qwen3-reranker-0.6b/model.onnx.data",
        sha256: "fbfe2bddcffc9e8b4a1145bf02f4ebc99119e57e38d32bf7f04172a7d0cf9c7c",
        size: 2383085568,
    },
    PinnedFile {
        path: "qwen3-reranker-0.6b/reranker.json",
        sha256: "513c2b90eed00b64142f4ad54a7bf8f211dd10e41f658164062e17a93b9f284e",
        size: 423,
    },
    PinnedFile {
        path: "qwen3-reranker-0.6b/tokenizer.json",
        sha256: "aeb13307a71acd8fe81861d94ad54ab689df773318809eed3cbe794b4492dae4",
        size: 11422654,
    },
];

pub const RUNTIMES: &[RuntimePin] = &[
    RuntimePin {
        os: "linux",
        arch: "x86_64",
        variant: "cpu",
        archives: &[Archive {
            url: "https://github.com/microsoft/onnxruntime/releases/download/v1.22.0/onnxruntime-linux-x64-1.22.0.tgz",
            sha256: "8344d55f93d5bc5021ce342db50f62079daf39aaafb5d311a451846228be49b3",
            size: 7798730,
        }],
        dylib: "onnxruntime-linux-x64-1.22.0/lib/libonnxruntime.so.1.22.0",
        colocate: &[],
    },
    RuntimePin {
        os: "linux",
        arch: "x86_64",
        variant: "gpu",
        archives: &[Archive {
            url: "https://github.com/microsoft/onnxruntime/releases/download/v1.22.0/onnxruntime-linux-x64-gpu-1.22.0.tgz",
            sha256: "2a19dbfa403672ec27378c3d40a68f793ac7a6327712cd0e8240a86be2b10c55",
            size: 227317516,
        }],
        dylib: "onnxruntime-linux-x64-gpu-1.22.0/lib/libonnxruntime.so.1.22.0",
        colocate: &[],
    },
    RuntimePin {
        os: "linux",
        arch: "aarch64",
        variant: "cpu",
        archives: &[Archive {
            url: "https://github.com/microsoft/onnxruntime/releases/download/v1.22.0/onnxruntime-linux-aarch64-1.22.0.tgz",
            sha256: "bb76395092d150b52c7092dc6b8f2fe4d80f0f3bf0416d2f269193e347e24702",
            size: 6849865,
        }],
        dylib: "onnxruntime-linux-aarch64-1.22.0/lib/libonnxruntime.so.1.22.0",
        colocate: &[],
    },
    RuntimePin {
        os: "macos",
        arch: "aarch64",
        variant: "coreml",
        archives: &[Archive {
            url: "https://github.com/microsoft/onnxruntime/releases/download/v1.22.0/onnxruntime-osx-arm64-1.22.0.tgz",
            sha256: "cab6dcbd77e7ec775390e7b73a8939d45fec3379b017c7cb74f5b204c1a1cc07",
            size: 25943843,
        }],
        dylib: "onnxruntime-osx-arm64-1.22.0/lib/libonnxruntime.1.22.0.dylib",
        colocate: &[],
    },
    RuntimePin {
        os: "windows",
        arch: "x86_64",
        variant: "directml",
        archives: &[
            Archive {
                url: "https://www.nuget.org/api/v2/package/Microsoft.ML.OnnxRuntime.DirectML/1.22.0",
                sha256: "29f9872d786236b79aa83f94482f3a17c14297e4833768d6d0ed4883ee732e60",
                size: 17898472,
            },
            Archive {
                url: "https://www.nuget.org/api/v2/package/Microsoft.AI.DirectML/1.15.4",
                sha256: "4e7cb7ddce8cf837a7a75dc029209b520ca0101470fcdf275c1f49736a3615b9",
                size: 202292617,
            },
        ],
        dylib: "runtimes/win-x64/native/onnxruntime.dll",
        colocate: &["bin/x64-win/DirectML.dll"],
    },
];
